name: Generate Mime Types

on:
  workflow_dispatch:
  push:
    paths:
      - "data/mime.types"
      - "data/mime.types.custom"
      - "stubs/mimeType.php.stub"

jobs:
  update:
    name: Generate Mime Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
           fetch-depth: 10

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
           php-version: 8.2
           extensions: mbstring, 
           coverage: xdebug,

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Setup Composer, install dependencies
        uses: ramsey/composer-install@v3
        with:
           composer-options: "--prefer-dist --optimize-autoloader"
           require-lock-file: "true"

      - name: Run update
        run: composer run-script generate-types

      - name: Run test suite
        run: composer run-script test

      - name: Coverage check
        run: composer run-script coverage-check

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
