name: Notify

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  setup:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: nearform-actions/github-action-notify-twitter@v1.1.5
        with:
          message: |
            ${{ github.event.repository.name }} ${{ github.event.release.tag_name }} has been released. Release notes: ${{ github.event.release.html_url }} #opensource #opensourcesoftware
          twitter-app-key: ${{ secrets.TWITTER_APP_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_APP_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
